version: '3.8'

services:

  postgres_approve:
    container_name: postgres_approve
    restart: always
    image: postgres:latest
    volumes:
      - volume_postgres_approve:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_approve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5493
    expose:
      - 5493
    ports:
      - "5493:5493"
    command: -p 5493

  approve_app:
    container_name: approve_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_SERVER: postgres_approve
    env_file:
      - .env
    depends_on:
      - postgres_approve
    ports:
      - "8070:8000"
    command: ./entrypoint.sh

volumes:
  volume_postgres_approve: {}


