version: '3.8'

services:

  db_documents:
    container_name: db_documents
    restart: always
    image: postgres:latest
    volumes:
      - volume_db_documents:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: documents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5491
    expose:
      - 5491
    ports:
      - "5491:5491"
    command: -p 5491

  approve_app:
    container_name: approve_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_SERVER: db_documents
    env_file:
      - .env
    depends_on:
      - db_documents
    ports:
      - "8070:8000"
    command: ./entrypoint.sh

volumes:
  volume_db_next_up: {}


